apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-http
  namespace: argocd
  labels:
    app: argocd
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: argo.corbe.net
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 80
