apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
data:
  8000: "default/icecast-source:8000"
  8001: "default/icecast-dnas:8001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast
  labels:
    app: icecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecast
  template:
    metadata:
      labels:
        app: icecast
    spec:
      containers:
      - name: icecast
        image: dcorbe/icecast:latest
        ports:
        - containerPort: 8000
        - containerPort: 8001
        volumeMounts:
          - mountPath: "/etc/icecast.xml"
            name: icecast-config
            subPath: "icecast.xml"
      volumes:
        - name: icecast-config
          configMap:
            name: icecast-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast-source-proxy
  labels:
    app: icecast-source-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icecast-source-proxy
  template:
    metadata:
      labels:
        app: icecast-source-proxy
    spec:
      containers:
        - name: icecast-source-proxy
          image: nginx:mainline-alpine
          ports:
            - containerPort: 8000
            - containerPort: 8001
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              name: icecast-source-proxy-config
              subPath: "nginx.conf"
      volumes:
        - name: icecast-source-proxy-config
          configMap:
            name: icecast-source-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: icecast
spec:
  selector:
    app: icecast
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: icecast-source
spec:
  type: ClusterIP
  selector:
    app: icecast
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: icecast-dnas
spec:
  type: ClusterIP
  selector:
    app: icecast
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: icecast-proxy
spec:
  type: LoadBalancer
  selector:
    app: icecast-source-proxy
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: port-dnas
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: port-source
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: icecast
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - hosts:
        - cast.corbe.net
      secretName: cast-tls
  rules:
    - host: cast.corbe.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: icecast
                port:
                  number: 80

