apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfspv
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  fstype: "zfs"
  poolname: "tank"
provisioner: zfs.csi.openebs.io