apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: www-data
      initContainers:
        - name: website-git-cloner
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/dcorbe/website.git
            - /data
          volumeMounts:
            - mountPath: /data
              name: www-data
      volumes:
        - name: www-data
          emptyDir: { }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: www.corbe.net
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
