apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  www.corbe.net corbe.net;

        location / {
            root   /usr/share/nginx/html/www.corbe.net;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location ~ \.php$ {
            root           html;
            fastcgi_pass   php-fpm:9000;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  /usr/share/nginx/html/www.corbe.net$fastcgi_script_name;
            include        fastcgi_params;
        }

        location ~ /\.ht {
            deny  all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: php-fpm
        image: php:fpm-alpine3.13
        ports:
        - containerPort: 9000
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: www-data
          - mountPath: "/tmp"
            name: php-sessions
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: www-data
          - mountPath: "/etc/nginx/conf.d/default.conf"
            name: nginx-config
            subPath: default.conf
      initContainers:
        - name: website-git-cloner
          image: alpine/git
          command:
            - /bin/sh
            - -c
            - |
              if [ ! "$(ls -A /data)"]; then
                git clone --single-branch -- https://github.com/dcorbe/website.git /data
              fi
          volumeMounts:
            - mountPath: /data
              name: www-data
      volumes:
        - name: www-data
          emptyDir: { }
        - name: php-sessions
          emptyDir: { }
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
spec:
  selector:
    app: webserver
  ports:
    - port: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: www.corbe.net
    cert-manager.io/issuer: "letsencrypt-production"
spec:
  tls:
    - hosts:
        - www.corbe.net
        - corbe.net
      secretName: corbe-tls
  rules:
  - host: corbe.net
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: nginx 
              port:
                number: 80
